### ISSUE TITLE
pt_BR translation to i18n

### ISSUE THREAD

**Issue by 4rm4** [traa-pixelcanvas/TimelapsePixelCanvas#7]
'pt_BR': {
            'only_time': '',
            'Bye': 'Até Logo!',
            'blind east of %s': 'Esse bot pode não ler pixels ao leste de %s',
            'blind south of %s': 'Esse bot pode não ler pixels ao sul de %s',
            'Loading chunk (%s, %s)...':'Carregando chunk (%s, %s)...',
            'rad > 5 prompt': 'Você tem certeza que deseja usar um  raio maior que 5?\nIsso aumentará o consumo do bot.\ny(Sim)/n(Não)\n',
            'Saved %s': 'Salvo %s',
            'Waiting %s seconds': 'Esperando %s segundos',
            'Quitting': 'Saindo',
            '>> Loading canvas [%s/%s]': '>> Carregando Canvas [%s/%s]'
        }

**Comment by Mismatchia** [comment]
Added in ba604c7533fabc11172956274327a4ed26bad57f. Thanks!
